
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules    
    ports:
      - '4000:4000'
    env_file:
      - .env.dev
    command: npm run dev
