
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: Roomy
    ports:
      - '4000:4000'
    env_file:
      - .env.prod
    depends_on:
      - mongodb
    restart: unless-stopped
    volumes:
      - .:/app
    command: npm start

  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log


  mongodb:
    image: mongo:7
    container_name: Roomy-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped


volumes:
  mongo_data: 